version: 2.1

orbs:
  terraform: circleci/terraform@3.1.0

parameters:
  terraform-organization:
    type: string
    default: "my-org"
  terraform-workspace:
    type: string
    default: "my-workspace"

executors:
  tf-executor:
    docker:
      - image: hashicorp/terraform:1.5.3

jobs:
  plan:
    executor: tf-executor
    steps:
      - checkout

      - run:
          name: Authenticate to Terraform Cloud
          command: |
            echo $TFC_TOKEN | terraform login --token

      - terraform/init:
          backend-config: |
            hostname=app.terraform.io
            organization=<< parameters.terraform-organization >>
            workspaces[name]=<< parameters.terraform-workspace >>

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan -input=false

      - store_artifacts:
          path: tfplan
          destination: terraform-plan-output

      - persist_to_workspace:
          root: .
          paths:
            - tfplan

  apply:
    executor: tf-executor
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Authenticate to Terraform Cloud
          command: |
            echo $TFC_TOKEN | terraform login --token

      - terraform/init:
          backend-config: |
            hostname=app.terraform.io
            organization=<< parameters.terraform-organization >>
            workspaces[name]=<< parameters.terraform-workspace >>

      - terraform/apply:
          plan: tfplan
          auto_approve: true

workflows:
  version: 2
  terraform-deploy:
    jobs:
      - plan:
          filters:
            branches:
              only: main

      - hold:
          type: approval
          requires:
            - plan

      - apply:
          requires:
            - hold
          filters:
            branches:
              only: main
